# Generated by Django 5.1.5 on 2025-01-30 03:18

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Photograph",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("legend", models.CharField(max_length=150)),
                ("description", models.TextField()),
                ("image", models.CharField(max_length=100)),
            ],
        ),
    ]
