# Generated by Django 5.1.5 on 2025-01-31 00:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gallery", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="photograph",
            name="category",
            field=models.CharField(
                choices=[
                    ("NEBULA", "Nebulosa"),
                    ("STAR", "Estrela"),
                    ("GALAXY", "Galáxia"),
                    ("PLANET", "Planeta"),
                ],
                default="NEBULA",
                max_length=100,
            ),
        ),
    ]
