# Generated by Django 5.1.5 on 2025-01-31 01:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gallery", "0002_photograph_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="photograph",
            name="published",
            field=models.BooleanField(default=False),
        ),
    ]
