# Generated by Django 5.1.5 on 2025-01-31 01:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gallery", "0003_photograph_published"),
    ]

    operations = [
        migrations.AddField(
            model_name="photograph",
            name="created_at",
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
