# Generated by Django 5.1.5 on 2025-01-31 02:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gallery", "0004_photograph_created_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="photograph",
            name="image",
            field=models.ImageField(blank=True, upload_to="photo/%Y/%m/%d"),
        ),
    ]
