# Generated by Django 5.1.5 on 2025-02-04 00:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gallery", "0006_photograph_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="photograph",
            name="published",
            field=models.BooleanField(default=True),
        ),
    ]
